name: birthdaycalculatorproject
services:
  birthdaycalculatorservice: 
    image:  leonecr/birthdaycalculator:latest
    container_name:  birthdaycalculator_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "8082:8082" # Mapeia a porta 8083 do  host  para a porta 8083 do contêiner ???. 
       - "4200:4200"   
    restart: always
