name: birthdaycalculatorproject
services:
  birthdaycalculatorservice: 
    image:  leonecr/birthdaycalculator:latest
    container_name:  birthdaycalculator_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "8083:80" # Mapeia a porta 8083 do  host  para a porta 8083 do contêiner ???.
       - "8084:4200" 
       - "4200:4200"    
       - "4000:4000"    
    restart: always
